-- =============================================
-- Gestion des Publicités - Taxi-brousse
-- =============================================
-- Fonctionnalité: Diffusion de vidéos publicitaires sur écrans dans les véhicules
-- Tarification: Prix par diffusion (défaut: 100 000 Ar)
-- =============================================

BEGIN;

-- ---------- Nettoyage ----------
DROP TABLE IF EXISTS depart_publicite CASCADE;
DROP TABLE IF EXISTS publicite CASCADE;
DROP TABLE IF EXISTS tarif_publicite CASCADE;
DROP TABLE IF EXISTS societe_publicitaire CASCADE;

-- ---------- Sociétés publicitaires ----------
CREATE TABLE societe_publicitaire (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    nom VARCHAR(200) NOT NULL,
    telephone VARCHAR(30),
    email VARCHAR(120),
    adresse TEXT,
    contact_nom VARCHAR(150),
    contact_telephone VARCHAR(30),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE societe_publicitaire IS 'Sociétés qui diffusent des vidéos publicitaires';
COMMENT ON COLUMN societe_publicitaire.actif IS 'Indique si la société est active';

-- ---------- Tarifs de diffusion ----------
CREATE TABLE tarif_publicite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_devise_id BIGINT NOT NULL,
    montant DECIMAL(12,2) NOT NULL CHECK (montant > 0),
    date_debut DATE NOT NULL DEFAULT CURRENT_DATE,
    date_fin DATE,
    description TEXT,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tarif_pub_devise FOREIGN KEY (ref_devise_id) REFERENCES ref_devise(id),
    CONSTRAINT ck_tarif_pub_dates CHECK (date_fin IS NULL OR date_fin >= date_debut)
);

COMMENT ON TABLE tarif_publicite IS 'Tarifs de diffusion des publicités (historique des prix)';
COMMENT ON COLUMN tarif_publicite.montant IS 'Prix par diffusion';
COMMENT ON COLUMN tarif_publicite.date_debut IS 'Date de début d''application du tarif';
COMMENT ON COLUMN tarif_publicite.date_fin IS 'Date de fin d''application du tarif (NULL = tarif actuel)';

-- ---------- Publicités (vidéos) ----------
CREATE TABLE publicite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    societe_publicitaire_id BIGINT NOT NULL,
    titre VARCHAR(200) NOT NULL,
    description TEXT,
    url_video VARCHAR(500),
    duree_secondes INTEGER CHECK (duree_secondes IS NULL OR duree_secondes > 0),
    date_debut_validite DATE NOT NULL,
    date_fin_validite DATE NOT NULL,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_publicite_societe FOREIGN KEY (societe_publicitaire_id) REFERENCES societe_publicitaire(id) ON DELETE CASCADE,
    CONSTRAINT ck_publicite_dates CHECK (date_fin_validite >= date_debut_validite)
);

COMMENT ON TABLE publicite IS 'Vidéos publicitaires créées par les sociétés';
COMMENT ON COLUMN publicite.url_video IS 'URL de stockage de la vidéo publicitaire';
COMMENT ON COLUMN publicite.duree_secondes IS 'Durée de la vidéo en secondes';
COMMENT ON COLUMN publicite.date_debut_validite IS 'Date à partir de laquelle la pub peut être diffusée';
COMMENT ON COLUMN publicite.date_fin_validite IS 'Date jusqu''à laquelle la pub peut être diffusée';

-- ---------- Diffusions (liaison départ-publicité) ----------
CREATE TABLE depart_publicite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depart_id BIGINT NOT NULL,
    publicite_id BIGINT NOT NULL,
    tarif_publicite_id BIGINT NOT NULL,
    date_diffusion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    montant_facture DECIMAL(12,2) NOT NULL CHECK (montant_facture >= 0),
    ref_devise_id BIGINT NOT NULL,
    statut_diffusion VARCHAR(30) NOT NULL DEFAULT 'PLANIFIE',
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_depart_pub_depart FOREIGN KEY (depart_id) REFERENCES depart(id) ON DELETE CASCADE,
    CONSTRAINT fk_depart_pub_publicite FOREIGN KEY (publicite_id) REFERENCES publicite(id) ON DELETE CASCADE,
    CONSTRAINT fk_depart_pub_tarif FOREIGN KEY (tarif_publicite_id) REFERENCES tarif_publicite(id),
    CONSTRAINT fk_depart_pub_devise FOREIGN KEY (ref_devise_id) REFERENCES ref_devise(id),
    CONSTRAINT ck_statut_diffusion CHECK (statut_diffusion IN ('PLANIFIE', 'DIFFUSE', 'ANNULE'))
);

COMMENT ON TABLE depart_publicite IS 'Chaque ligne représente UNE DIFFUSION d''une publicité sur un départ';
COMMENT ON COLUMN depart_publicite.date_diffusion IS 'Date et heure de la diffusion';
COMMENT ON COLUMN depart_publicite.montant_facture IS 'Montant facturé pour cette diffusion (copie du tarif au moment de la diffusion)';
COMMENT ON COLUMN depart_publicite.statut_diffusion IS 'PLANIFIE=prévu, DIFFUSE=effectué, ANNULE=annulé';

-- ---------- Index pour performance ----------
CREATE INDEX idx_depart_publicite_depart ON depart_publicite(depart_id);
CREATE INDEX idx_depart_publicite_publicite ON depart_publicite(publicite_id);
CREATE INDEX idx_depart_publicite_date ON depart_publicite(date_diffusion);
CREATE INDEX idx_depart_publicite_societe ON depart_publicite(publicite_id, date_diffusion);
CREATE INDEX idx_publicite_societe ON publicite(societe_publicitaire_id);
CREATE INDEX idx_publicite_dates ON publicite(date_debut_validite, date_fin_validite) WHERE actif = TRUE;
CREATE INDEX idx_tarif_publicite_actif ON tarif_publicite(date_debut, date_fin) WHERE actif = TRUE;

-- ---------- Fonction helper : récupérer le tarif actuel ----------
CREATE OR REPLACE FUNCTION get_tarif_publicite_actuel(p_date DATE DEFAULT CURRENT_DATE)
RETURNS TABLE (
    id BIGINT,
    montant DECIMAL(12,2),
    devise_code VARCHAR(10)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        tp.id,
        tp.montant,
        rd.code
    FROM tarif_publicite tp
    JOIN ref_devise rd ON tp.ref_devise_id = rd.id
    WHERE tp.actif = TRUE
      AND tp.date_debut <= p_date
      AND (tp.date_fin IS NULL OR tp.date_fin >= p_date)
    ORDER BY tp.date_debut DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;


-- ---------- Données initiales ----------
-- Tarif par défaut : 100 000 Ar par diffusion
INSERT INTO tarif_publicite (ref_devise_id, montant, date_debut, date_fin, description, actif) VALUES
((SELECT id FROM ref_devise WHERE code = 'MGA'), 100000.00, '2025-01-01', NULL, 'Tarif standard de diffusion publicitaire', TRUE)
ON CONFLICT DO NOTHING;

-- Sociétés publicitaires exemples
INSERT INTO societe_publicitaire (code, nom, email, telephone, adresse, actif) VALUES
('SOC-PUB-001', 'Vaniala', 'contact@vaniala.mg', '+261 20 22 123 45', 'Antananarivo, Madagascar', TRUE),
('SOC-PUB-002', 'Lewis', 'marketing@lewis.mg', '+261 20 22 678 90', 'Antananarivo, Madagascar', TRUE);


COMMIT;

-- ---------- Requêtes de vérification ----------
SELECT 'Sociétés publicitaires créées:', COUNT(*) FROM societe_publicitaire;
SELECT 'Tarifs créés:', COUNT(*) FROM tarif_publicite;

-- =============================================
-- EXEMPLE D'UTILISATION : CA Décembre 2025
-- =============================================

-- Requête pour calculer le CA de décembre 2025
-- SELECT * FROM v_ca_mensuel_diffusions WHERE annee = 2025 AND mois = 12;

-- Résultat attendu avec les données de l'énoncé :
-- Vaniala : 20 diffusions × 100 000 Ar = 2 000 000 Ar
-- Lewis   : 10 diffusions × 100 000 Ar = 1 000 000 Ar
-- TOTAL CA Décembre 2025 : 3 000 000 Ar
